version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 3.0
    commands:
      - cd ..
      # TODO: Temporary - fix the dafny script to not use which instead!
      # See https://github.com/dafny-lang/dafny/issues/449
      - yum install -y which
      - yum install -y nuget
      - npm install bignumber.js
      - pip install lit OutputCheck pyyaml
      - find . -type f
      # Get Boogie
      - git clone https://github.com/boogie-org/boogie.git
      - nuget restore boogie/Source/Boogie.sln
      - msbuild boogie/Source/Boogie.sln
      # Get Z3
      - wget https://github.com/Z3Prover/z3/releases/download/z3-4.8.4/z3-4.8.4.d6df51951f4c-x64-ubuntu-14.04.zip
      - unzip z3*.zip && rm *.zip
      - cp -r z3* dafny/Binaries/z3
      # NuGet
      - cd dafny.msbuild
      - dotnet restore Source/dafny.msbuild.sln
  build:
    commands:
      - dotnet build Source/dafny.msbuild.sln
      - cd Test
      - dotnet build -t:VerifyDafny
      - dotnet test
